services:
  - type: web
    name: chess-backend
    env: node
    buildCommand: npm install
    startCommand: node serverBackEnd.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: STOCKFISH_API_URL
        value: https://chess-stockfish-server.onrender.com
    rootDir: server/backend

  - type: web
    name: chess-stockfish
    env: python
    python:
      version: "3.9.16"
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -e .
    startCommand: python stockfish_server.py
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: true
    rootDir: server/stockfish
